# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_version: 14.0
org_name: Vladimir
org_slug: Volodiay616
rebel_module_groups: []
repo_description: My solution of Odoo 14 tutorial
repo_name: Odoo 14 tutorial
repo_slug: tutorials
repo_website: https://github.com/Volodiay616/tutorials
travis_apt_packages: []
travis_apt_sources: []

